### ISSUE TITLE
Use x11docker?

### ISSUE THREAD

**Issue by pataquets** [deddu/nyxt-docker#12]
I'm using [x11docker](https://github.com/mviereck/x11docker) to run my own source build Docker image. It's quite handy.

Maybe it could be useful to mention it in the docs.

**Comment by deddu** [comment]
Does X11docker work on Mac? The readme of the repo says it’s not supported. That is one of the items that would be ideal indeed , we discussed about it in passing in issue #7 . We can definitely mention that in the readme.
